version: '3.3'
services:
  postgres:
    build: servicesData/postgresdb/
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5433:5432
    volumes:
      - ./blockstorage/postgres:/var/lib/postgresql/dataz
  clientes-microservicio:
    image: jovaniac/cliente-ms:0.0.1-snapshot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bank_ito
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  