version: '3.3'
services:
  discovery-server:
    image: jovaniac/eureka-discovery-gateway:0.0.1-snapshot
    ports:
      - 8761:8761
  gateway-server-:
    image: jovaniac/api-gateway-server-gateway:0.0.1-snapshot
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - 8766:8766
  monitor:
    image: jovaniac/monitor-server-gateway:0.0.1-snapshot
    ports:
      - 8090:8090
  postgres:
    build: servicesData/postgresdb/
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./blockstorage/postgres:/var/lib/postgresql/dataz
  rabbitmq:
    image: rabbitmq:3.6.12-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
  