version: '3.3'
services:
  discovery-server-:
    image: jovaniac/eureka-discovery-gateway:0.0.1-snapshot
    ports:
      - 8761:8761
  postgres:
    build: servicesData/postgresdb/
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./blockstorage/postgres:/var/lib/postgresql/dataz